3.9 Мы продолжаем работать с датасетом Pandas practices . Исследуйте данные и ответьте на вопросы:

1. Водителей какого пола в датасете больше?

In [6]:
import pandas as pd

data = pd.read_csv("police.csv", sep=",")


countsNull = data.isnull().sum()


max_null_column = countsNull.idxmax()
# max_null_count = countsNull.max()

data.drop(max_null_column, inplace=True, axis=1)
print(data.driver_gender.str.contains("M").value_counts())
gender_counts = data.driver_gender.value_counts()
print(f"Количество мужчин: {gender_counts.get('M', 0)}")
print(f"Количество женщин: {gender_counts.get('F', 0)}")

driver_gender
True     62895
False    23511
Name: count, dtype: int64
Количество мужчин: 62895
Количество женщин: 23511

Чтобы получить ответ на вопрос, водителей какого пола чаще останавливают

In [7]:
data['driver_gender'].value_counts(normalize=True)

driver_gender
M    0.727901
F    0.272099
Name: proportion, dtype: float64

Что нужно сделать:

1.	создайте Python-ноутбук, загрузите в него данные из csv-файла и преобразуйте в объект DataFrame;


По каждому пункту задания сделайте выводы и отразите их в своем Python-ноутбуке. В качестве решения задания прикрепите ссылку на ноутбук.

In [9]:
dt = pd.read_csv("data.csv")
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Country                  660 non-null    object
 1   League                   660 non-null    object
 2   Club                     626 non-null    object
 3   Player Names             660 non-null    object
 4   Matches_Played           660 non-null    int64
 5   Substitution             660 non-null    int64
 6   Mins                     660 non-null    int64
 7   Goals                    660 non-null    int64
 8   xG                       660 non-null    float64
 9   xG Per Avg Match         660 non-null    float64
 10  Shots                    660 non-null    int64
 11  OnTarget                 660 non-null    int64
 12  Shots Per Avg Match      660 non-null    float64
 13  On Target Per Avg Match  660 non-null    float64
 14  Year                     660 non-null    int64
dtypes: float64(4), int64(7), object(4)
memory usage: 77.5+ KB

2. просмотрите полученный объект;

In [10]:
dt.head()

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016

3.	вычислите описательные статистики для DataFrame;

In [17]:
print("mean goals =", dt.Goals.mean())
print("median shots =", dt.Shots.median())

mean goals = 11.784848484848485
median shots = 62.0

4.	поразмышляйте, как вы можете использовать срезы для анализа вашего набора данных, получите необходимый срез(ы) DataFrame;

In [22]:
dt.iloc[2:4, 4:10]

   Matches_Played  Substitution   Mins  Goals     xG  xG Per Avg Match
2              34              1  2940     28  23.21              0.75
3              32              3  2842     13  14.06              0.47

In [24]:
dt[dt.Goals > 20]

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
5,Spain,La Liga,(JUV),Cristiano Ronaldo,29,0,2634,25,24.68,0.89,162,60,5.84,2.16,2016
12,Spain,La Liga,(BAR),Lionel Messi,32,2,2910,37,26.65,0.87,179,76,5.84,2.48,2016
22,Italy,Serie A,(LAZ),Ciro Immobile,35,1,3294,22,19.76,0.57,136,98,3.92,2.83,2016
24,Italy,Serie A,(NAP),Dries Mertens,28,7,2671,28,21.65,0.77,148,102,5.26,3.63,2016
29,Italy,Serie A,(PSG),Mauro Icardi,34,0,3188,24,19.13,0.57,109,52,3.25,1.55,2016
32,Italy,Serie A,(ROM),Edin Dzeko,33,4,3194,29,30.60,0.91,178,99,5.29,2.94,2016
37,Italy,Serie A,(IMI),Gonzalo Higuain,32,6,3138,24,17.84,0.54,134,91,4.06,2.75,2016
39,Italy,Serie A,(TOR),Andrea Belotti,34,1,3241,26,19.45,0.57,130,78,3.81,2.29,2016
46,Germany,Bundesliga,(BAY),Robert Lewandowski,31,2,2871,30,30.52,1.01,143,86,4.73,2.85,2016
48,Germany,Bundesliga,(CHE),Timo Werner,28,3,2496,21,12.61,0.48,74,50,2.82,1.90,2016
54,Germany,Bundesliga,(ARS),Pierre-Emerick Aubameyang,31,1,2894,31,28.94,0.95,116,78,3.81,2.56,2016
58,Germany,Bundesliga,(KOL),Anthony Modeste,34,0,3075,25,19.74,0.61,101,53,3.12,1.64,2016
60,England,Premier League,(INT),Alexis Sanchez,36,2,3385,24,19.24,0.54,129,49,3.62,1.38,2016
61,England,Premier League,(INT),Romelu Lukaku,36,1,3448,25,18.15,0.50,110,53,3.03,1.46,2016
62,England,Premier League,(TOT),Harry Kane,29,1,2636,29,18.87,0.68,110,58,3.96,2.09,2016
72,England,Premier League,(MNC),Sergio Aguero,25,6,2444,21,22.38,0.87,139,51,5.40,1.98,2016
102,Spain,La Liga,(CEL),Iago Aspas,33,1,3053,22,19.92,0.62,94,43,2.92,1.34,2017
105,Spain,La Liga,(ATL),Luis Suarez,32,1,3008,25,25.65,0.81,121,55,3.82,1.74,2017
107,Spain,La Liga,(BAR),Lionel Messi,32,4,3123,33,32.54,0.99,197,95,5.99,2.89,2017
112,Spain,La Liga,(JUV),Cristiano Ronaldo,27,0,2375,26,29.00,1.16,178,76,7.12,3.04,2017
115,Spain,La Liga,(GIR),Cristhian Stuani,32,1,2785,21,20.52,0.70,74,37,2.52,1.26,2017
123,Italy,Serie A,(JUV),Paulo Dybala,26,7,2407,22,11.40,0.45,114,45,4.50,1.78,2017
135,Italy,Serie A,(LAZ),Ciro Immobile,33,0,2799,29,19.15,0.65,110,53,3.73,1.80,2017
137,Italy,Serie A,(PSG),Mauro Icardi,34,0,3096,29,23.14,0.71,101,53,3.10,1.63,2017
140,Germany,Bundesliga,(BAY),Robert Lewandowski,24,6,2247,29,26.49,1.12,127,54,5.37,2.28,2017
180,Spain,La Liga,(RMA),Karim Benzema,35,1,3072,21,17.46,0.54,104,44,3.22,1.36,2018
188,Spain,La Liga,(ATL),Luis Suarez,31,2,2954,21,24.88,0.80,112,58,3.60,1.87,2018
195,Spain,La Liga,(BAR),Lionel Messi,29,5,2849,36,25.49,0.85,170,87,5.67,2.90,2018
201,Italy,Serie A,(ATA),Duvan Zapata,32,5,3064,23,18.38,0.57,118,50,3.66,1.55,2018
203,Italy,Serie A,(JUV),Cristiano Ronaldo,30,1,2857,21,21.65,0.72,177,68,5.89,2.26,2018
206,Italy,Serie A,(SAM),Fabio Quagliarella,37,0,3269,26,23.06,0.67,141,57,4.10,1.66,2018
219,Italy,Serie A,(BSC),Krzysztof Piatek,34,3,3147,23,17.23,0.52,118,52,3.56,1.57,2018
238,Germany,Bundesliga,(BAY),Robert Lewandowski,33,0,3090,22,29.27,0.90,144,51,4.43,1.57,2018
242,France,France Ligue 2,(ARS),Nicolas Pepe,37,1,3533,22,20.08,0.54,118,60,3.17,1.61,2018
251,France,France Ligue 1,(PSG),Kylian Mbappe-Lottin,24,5,2488,33,31.17,1.19,125,70,4.77,2.67,2018
263,England,Premier League,(LIV),Mohamed Salah,37,1,3417,22,20.50,0.57,137,63,3.81,1.75,2018
267,England,Premier League,(LIV),Sadio Mane,35,1,3236,22,15.33,0.45,87,42,2.55,1.23,2018
271,England,Premier League,(MNC),Sergio Aguero,31,2,2566,21,19.45,0.72,118,43,4.37,1.59,2018
273,England,Premier League,(ARS),Pierre-Emerick Aubameyang,30,6,2905,22,21.71,0.71,94,39,3.07,1.28,2018
301,USA,MLS,(ATA),Josef Martinez,32,0,3050,28,25.04,0.78,128,52,3.99,1.62,2019
302,USA,MLS,(ACM),Zlatan Ibrahimovic,31,0,2998,31,22.72,0.72,159,67,5.04,2.12,2019
317,USA,MLS,(LAF),Carlos Vela,33,0,3128,36,25.35,0.77,167,75,5.07,2.28,2019
321,Spain,La Liga,(RMA),Karim Benzema,36,1,3207,21,21.61,0.64,124,59,3.67,1.75,2019
333,Spain,La Liga,(BAR),Lionel Messi,32,1,3067,25,21.63,0.67,159,68,4.93,2.11,2019
381,Italy,Serie A,(INT),Romelu Lukaku,33,3,3156,23,18.94,0.57,99,47,2.98,1.41,2019
382,Italy,Serie A,(Sassuolo ),Francesco Caputo,33,3,3125,21,13.82,0.42,73,35,2.22,1.06,2019
385,Italy,Serie A,(JUV),Cristiano Ronaldo,33,0,3127,31,27.32,0.83,208,79,6.32,2.40,2019
391,Italy,Serie A,(LAZ),Ciro Immobile,36,1,3371,36,26.61,0.75,142,71,4.00,2.00,2019
401,Germany,Bundesliga,(CHE),Timo Werner,33,1,2744,28,20.80,0.72,123,63,4.26,2.18,2019
408,Germany,Bundesliga,(BAY),Robert Lewandowski,31,0,2783,34,31.05,1.06,138,67,4.71,2.29,2019
443,England,Premier League,(LEI),Jamie Vardy,34,1,3271,23,19.28,0.56,89,42,2.58,1.22,2019
453,England,Premier League,(SOU),Danny Ings,32,6,3009,22,16.79,0.53,93,37,2.94,1.17,2019
454,England,Premier League,(ARS),Pierre-Emerick Aubameyang,35,1,3392,22,16.07,0.45,93,42,2.60,1.18,2019
473,Brazil,Campeonato Brasileiro SÃ©rie A,(FLA),Gabriel Barbosa,29,0,2716,25,24.59,0.86,117,62,4.09,2.17,2019
475,Brazil,Campeonato Brasileiro SÃ©rie A,(FLA),Bruno Henrique,29,4,2822,21,21.09,0.71,98,46,3.30,1.55,2019

5.	определите, какую полезную информацию, вы можете получить о данных, используя отбор и фильтрацию, сформируйте необходимый поднабор данных и проанализируйте его





6.	выполните сортировку применительно к исследуемому набору данных

In [33]:
top_scorers = dt.sort_values('Goals', ascending=False)[['Player Names', 'Goals']].dropna().head(5)
print(top_scorers)
top_scorers = dt.sort_values('Goals')[['Player Names', 'Goals']].dropna().head(5)
top_scorers

           Player Names  Goals
12         Lionel Messi     37
391       Ciro Immobile     36
317         Carlos Vela     36
195        Lionel Messi     36
408  Robert Lewandowski     34

       Player Names  Goals
375   Andraz Sporar      2
362  Douglas Tanque      2
359    Alex Telles       2
377    Bruno Duarte      2
352     Andre Andre      2

7.	потренируйтесь в переименование колонок исследуемого DataFrame;

In [42]:
dt2 = dt.rename(columns={'Club': 'ClubNew'})
dt2

,Country,League,ClubNew,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Netherlands,Eredivisie,(UTR),Gyrano Kerk,24,0,2155,10,7.49,0.33,50,18,2.20,0.79,2020
656,Netherlands,Eredivisie,(AJA),Quincy Promes,18,2,1573,12,9.77,0.59,56,30,3.38,1.81,2020
657,Netherlands,Eredivisie,(PSV),Denzel Dumfries,25,0,2363,7,5.72,0.23,45,14,1.81,0.56,2020
658,Netherlands,Eredivisie,NaN,Cyriel Dessers,26,0,2461,15,14.51,0.56,84,43,3.24,1.66,2020
659,Netherlands,Eredivisie,(PSV),Cody Gakpo,14,11,1557,7,4.43,0.27,38,15,2.32,0.92,2020

8.	проверьте DataFrame на наличие пропущенных значений, выберите один из методов работы с пропусками и примените его;

In [52]:
dt3 = dt.dropna()
dt3
# data.dropna(subset=['Certificate', 'Rating']).isnull().mean()

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,Netherlands,Eredivisie,(RZA),Haris Vuckic,23,2,2194,11,6.00,0.26,38,17,1.65,0.74,2020
655,Netherlands,Eredivisie,(UTR),Gyrano Kerk,24,0,2155,10,7.49,0.33,50,18,2.20,0.79,2020
656,Netherlands,Eredivisie,(AJA),Quincy Promes,18,2,1573,12,9.77,0.59,56,30,3.38,1.81,2020
657,Netherlands,Eredivisie,(PSV),Denzel Dumfries,25,0,2363,7,5.72,0.23,45,14,1.81,0.56,2020
659,Netherlands,Eredivisie,(PSV),Cody Gakpo,14,11,1557,7,4.43,0.27,38,15,2.32,0.92,2020

9. проверьте DataFrame на наличие дубликатов;

In [53]:
dt.duplicated().sum()

0

10.	сделайте предположение, какой новый признак вы могли бы ввести для исследуемого набора данных, и реализуйте его в созданном DataFrame.

In [56]:
dt['Goals_per_Min'] = dt['Goals'] / dt['Mins']
dt['Goals_per_Min'].head(5)

0    0.005949
1    0.005113
2    0.009524
3    0.004574
4    0.007450
Name: Goals_per_Min, dtype: float64

<b>Итого:</b>
1. Загрузка данных: Данные успешно загружены из CSV-файла в DataFrame.
2. Просмотр объекта: Получен первый взгляд на структуру и содержание данных.
3. Описательные статистики: Описательные статистики предоставляют некоторые метрики для числовых данных.
4. Использование срезов: Срезы позволяют извлекать подмножества данных для дальнейшего анализа.
5. Отбор и фильтрация: Фильтрация помогает сосредоточиться на нужных нам данных.
6. Сортировка: Сортировка данных облегчает анализ и поиск ключевых значений.
7. Переименование колонок: Переименование колонок помогает сделать код более читаемым.
8. Проверка на пропуски: Проверка на пропуски позволяет выявить неполные данные.
9. Работа с пропусками: Применение метода для обработки пропусков обеспечивает чистоту данных.
10. Проверка на дубликаты: Проверка на дубликаты помогает поддерживать уникальность записей.
11. Создание нового признака: Введение нового признака углубляет анализ и помогает оценить эффективность игроков.